# Generated by Django 2.1.5 on 2019-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
